# version: '3.8'

services:
  # שירות מסד הנתונים
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game_db
    ports:
      - "5433:5432"

  # שירות האפליקציה שלך
  app:
    build: .
    depends_on:
      - db
    environment:
      # כתובת החיבור למסד הנתונים (שימי לב ששם המארח הוא 'db')
      DATABASE_URL: "postgresql://user:password@db:5432/game_db?schema=public"
    # דרישות הרצה קריטיות: הרצת מיגרציות ואז את הקוד 
    # השורה למטה היא השינוי - אנחנו מוסיפים המתנה של 5 שניות
    command: sh -c "sleep 5 && npx prisma db push && node main.js"
      